//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsInShas.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordsInShas.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;word&quot;,&quot;instances&quot;
        ///&quot;אמר&quot;,&quot;35791&quot;
        ///&quot;לא&quot;,&quot;28963&quot;
        ///&quot;רב&quot;,&quot;17674&quot;
        ///&quot;ליה&quot;,&quot;16210&quot;
        ///&quot;אלא&quot;,&quot;15092&quot;
        ///&quot;רבי&quot;,&quot;13351&quot;
        ///&quot;על&quot;,&quot;11622&quot;
        ///&quot;את&quot;,&quot;10297&quot;
        ///&quot;אין&quot;,&quot;9598&quot;
        ///&quot;ולא&quot;,&quot;9586&quot;
        ///&quot;הוא&quot;,&quot;9206&quot;
        ///&quot;אומר&quot;,&quot;9103&quot;
        ///&quot;מאי&quot;,&quot;9096&quot;
        ///&quot;כל&quot;,&quot;8709&quot;
        ///&quot;לו&quot;,&quot;8673&quot;
        ///&quot;בר&quot;,&quot;8275&quot;
        ///&quot;לה&quot;,&quot;7507&quot;
        ///&quot;ר&apos;&quot;,&quot;7476&quot;
        ///&quot;של&quot;,&quot;7340&quot;
        ///&quot;יהודה&quot;,&quot;7252&quot;
        ///&quot;נמי&quot;,&quot;6858&quot;
        ///&quot;הא&quot;,&quot;6833&quot;
        ///&quot;אל&quot;,&quot;6314&quot;
        ///&quot;דאמר&quot;,&quot;6169&quot;
        ///&quot;אי&quot;,&quot;6148&quot;
        ///&quot;בן&quot;,&quot;6031&quot;
        ///&quot;אבל&quot;,&quot;5780&quot;
        ///&quot;כי&quot;,&quot;5739&quot;
        ///&quot;משום&quot;,&quot;5360....
        /// </summary>
        internal static string CommonWords {
            get {
                return ResourceManager.GetString("CommonWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string HtmlTemplate {
            get {
                return ResourceManager.GetString("HtmlTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf - 8&quot;?&gt;
        ///&lt;shas&gt;
        ///&lt;amud&gt;&lt;m&gt;Arachin&lt;/m&gt;&lt;d&gt;2&lt;/d&gt;&lt;a&gt;1&lt;/a&gt;&lt;t&gt;הכל מעריכין ונערכין נודרין ונידרין כהנים לוים וישראלים נשים ועבדים טומטום ואנדרוגינוס נודרין ונידרין ומעריכין אבל לא נערכין שאינו נערך אלא הזכר ודאי ונקבה ודאית חרש שוטה וקטן נידרין ונערכין אבל לא נודרין ולא מעריכין מפני שאין בהם דעת הכל מעריכין לאתויי מאי לאתויי מופלא סמוך לאיש נערכין לאתויי מאי לאתויי מנוול ומוכה שחין סד&quot;א נדר בערכך כתיב כל שישנו בדמים ישנו בערכין וכל שאינו בדמים אינו בערכין קמ&quot;ל נפשות כל דהו נודרין ל [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShasData {
            get {
                return ResourceManager.GetString("ShasData", resourceCulture);
            }
        }
    }
}
